variables:
  PROJECT_MODULES: "group_master"
  ODOO_VERSION: "12.0"

stages:
  - build

tests:
  stage: build
  script:
  - virtualenv env
  - source env/bin/activate
  - pip install -r requirements.txt
  - git clone --quiet --depth=1 --branch=$ODOO_VERSION https://github.com/eezee-it/odoo.git env/odoo
  - rm -rf env/odoo/.git